name: plaid-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.3
  - r-devtools
  - r-remotes
  - r-matrix
  - r-matrixstats
  - r-rfast
  - bioconductor-sparsematrixstats
  - r-qlcmatrix
  - bioconductor-biocstyle
  - r-knitr
  - r-rmarkdown
  - r-testthat
